### ISSUE TITLE
is it possible to cross-compile for arm?

### ISSUE THREAD

**Issue by belkone** [KoynovStas/wsdd#10]
Hi, 
I'm trying to cross-compile your awesome project to arm but without luck.
Is it possible? 
I changed: 
`GCC              ?=  arm-linux-gnueabihf-g++`
`CC              ?=  arm-linux-gnueabihf-g++`
`LDFLAGS          ?=  -static-libstdc++`
`CFLAGS           += -std=c++11 -O2  -Wall  -pipe`
and added `$(LDFLAGS)` to `$(GCC)` references, for example:
`$(CC) $(LDFLAGS) -c $< -o $@  $(CFLAGS)`
Could you please support me?

**Comment by KoynovStas** [comment]
`GCC ?= arm-linux-gnueabihf-g++` its old style, need use CC! update to last version!

Just do it:
`make CC=arm-linux-gnueabihf-gcc`

**Comment by belkone** [comment]
indeed! thank you so much :)
