### ISSUE TITLE
debug.log how to use?

### ISSUE THREAD

**Issue by Nigelwz** [KoynovStas/wsdd#6]
Hi,
 I want to use gsoap onvif ,how can I use generate *.log file see 
```c
daemon_error_exit()
```
?
thanks

**Comment by KoynovStas** [comment]
This function works as a `printf`, it print to the error console. if you need it to print to a file (*.log), you should use a stream pointer for your file.
`int vfprintf(FILE *stream, const char *format, va_list ap);`

see[ man page](https://linux.die.net/man/3/vfprintf)

**Comment by Nigelwz** [comment]
Hi ok I Know thanks,
By the way, I use onvif device tool on ubantu
but I can see some error on tool.
![IMG_1868](https://user-images.githubusercontent.com/18673071/67189595-15e5f180-f421-11e9-9956-e280b06b9e11.jpg)

thank your reply.

**Comment by KoynovStas** [comment]
:)
see define `DAEMON_NO_CLOSE_STDIO = 0 ` in Makefile.
find this macro in the code and you will understand!

**Comment by Nigelwz** [comment]
OK thanks, I will check

**Comment by Nigelwz** [comment]
Hi ,
   I think the Define description do not related my error messange.
the log seem like I have some setting which has problem.
Do you have test the code with onvif test tool on ubantu?

thanks your repley.

**Comment by KoynovStas** [comment]
No I used free [ONVIF Device Manager](https://sourceforge.net/projects/onvifdm/)
You can uses ONVIF Device Test Tool for windows.
